# Questão 5

Repita o problema na questão 4 considerado agora o método do K-means ou k-médias, que é uma técnica de clusterização por particionamento.


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans #https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

x1 = np.array([0.88,0.90,0.90,0.87,0.93,0.89,0.88,0.81,0.82,0.85,0.77,0.71,0.75,0.70,0.44,0.47,0.23,0.34,0.31,0.24,0.76]) #Atributo 1
x2 = np.array([0.99,0.99,0.98,0.98,0.93,0.97,0.87,0.92,0.92,0.90,0.85,0.83,0.83,0.62,0.58,0.37,0.33,0.36,0.35,0.37,0.80])
x3 = np.array([0.91,0.93,0.94,0.97,0.93,0.92,0.91,0.80,0.75,0.64,0.69,0.72,0.63,0.60,0.37,0.45,0.27,0.51,0.32,0.36,0.61])
x4 = np.array([1.10,1.26,1.24,1.18,1.20,1.04,1.41,0.55,1.05,0.07,-1.36,0.47,-0.87,0.21,-1.36,-0.68,-1.26,-1.98,-0.55,0.20,0.39])

dados = []
for i,j,k,l in zip(x1,x2,x3,x4):
    dados.append([i,j,k,l])
dados = np.array(dados)
print('Dados=\n'+str(dados))


k = KMeans(n_clusters=6, random_state=0).fit(dados)
print('centros=\n'+str(k.cluster_centers_))
#print('labels=\n'+str(k.labels_))


Dados=
[[ 0.88  0.99  0.91  1.1 ]
 [ 0.9   0.99  0.93  1.26]
 [ 0.9   0.98  0.94  1.24]
 [ 0.87  0.98  0.97  1.18]
 [ 0.93  0.93  0.93  1.2 ]
 [ 0.89  0.97  0.92  1.04]
 [ 0.88  0.87  0.91  1.41]
 [ 0.81  0.92  0.8   0.55]
 [ 0.82  0.92  0.75  1.05]
 [ 0.85  0.9   0.64  0.07]
 [ 0.77  0.85  0.69 -1.36]
 [ 0.71  0.83  0.72  0.47]
 [ 0.75  0.83  0.63 -0.87]
 [ 0.7   0.62  0.6   0.21]
 [ 0.44  0.58  0.37 -1.36]
 [ 0.47  0.37  0.45 -0.68]
 [ 0.23  0.33  0.27 -1.26]
 [ 0.34  0.36  0.51 -1.98]
 [ 0.31  0.35  0.32 -0.55]
 [ 0.24  0.37  0.36  0.2 ]
 [ 0.76  0.8   0.61  0.39]]
centros=
[[ 0.766       0.814       0.674       0.338     ]
 [ 0.76        0.84        0.66       -1.115     ]
 [ 0.88375     0.95375     0.9075      1.185     ]
 [ 0.33666667  0.42333333  0.38333333 -1.53333333]
 [ 0.24        0.37        0.36        0.2       ]
 [ 0.39        0.36        0.385      -0.615     ]]
